// Generates supabase/seed.sql from the app's demo companies and jobs.
//
//   dart run tool/generate_seed.dart
//
// Job dates are written relative to the day you run it, so re-run and
// re-seed when the demo deadlines pass.
import 'dart:convert';
import 'dart:io';

import 'package:vocation_sl/data/demo/demo_companies.dart';
import 'package:vocation_sl/data/demo/demo_jobs.dart';

String q(Object? v) {
  if (v == null) return 'null';
  if (v is num || v is bool) return '$v';
  if (v is List || v is Map) return "'${jsonEncode(v).replaceAll("'", "''")}'::jsonb";
  return "'${v.toString().replaceAll("'", "''")}'";
}

void main() {
  final b = StringBuffer()
    ..writeln('-- Generated by tool/generate_seed.dart on ${DateTime.now().toIso8601String()}')
    ..writeln('-- Fictional demo employers and jobs. Safe to re-run (upserts).')
    ..writeln();

  for (final c in demoCompanies) {
    final j = c.toJson();
    final cols = j.keys.join(', ');
    final vals = j.values.map(q).join(', ');
    final updates = j.keys.where((k) => k != 'id').map((k) => '$k = excluded.$k').join(', ');
    b.writeln('insert into public.companies ($cols) values ($vals) on conflict (id) do update set $updates;');
  }
  b.writeln();

  for (final job in buildDemoJobs(DateTime.now())) {
    final j = job.toJson(includeCompany: false);
    final cols = j.keys.join(', ');
    final vals = j.values.map(q).join(', ');
    final updates = j.keys.where((k) => k != 'id').map((k) => '$k = excluded.$k').join(', ');
    b.writeln('insert into public.jobs ($cols) values ($vals) on conflict (id) do update set $updates;');
  }

  final out = File('supabase/seed.sql')..writeAsStringSync(b.toString());
  stdout.writeln('Wrote ${out.path} (${demoCompanies.length} companies, ${buildDemoJobs(DateTime.now()).length} jobs)');
}
