import 'package:flutter/foundation.dart' show kIsWeb;

/// Build-time configuration.
///
/// Supabase is enabled by passing both values at build time:
///   flutter run --dart-define=SUPABASE_URL=https://xyz.supabase.co \
///               --dart-define=SUPABASE_PUBLISHABLE_KEY=sb_publishable_...
/// Without them the app runs entirely on the built-in demo backend.
class AppConfig {
  static const supabaseUrl = String.fromEnvironment('SUPABASE_URL');
  static const supabaseKey = String.fromEnvironment('SUPABASE_PUBLISHABLE_KEY');

  static bool get useSupabase => supabaseUrl.isNotEmpty && supabaseKey.isNotEmpty;

  /// Web push key from Firebase → Project settings → Cloud Messaging →
  /// Web Push certificates. Not secret. Firebase project settings themselves
  /// live in lib/firebase_options.dart (generated by flutterfire configure).
  static const firebaseVapidKey = String.fromEnvironment(
    'FIREBASE_VAPID_KEY',
    defaultValue: 'BMvqa50cs94jIC-Zzf2_7xUuPDTknYJnasUQNtc0D0bYe7S2IvyQK6gwe19YZ3ScFM6TSSrZFACzDmRULEoU64w',
  );

  /// Deep link the mobile apps receive after Google sign-in, email
  /// confirmation and password reset. Must be listed in Supabase
  /// Authentication → URL Configuration → Redirect URLs.
  static const mobileAuthRedirect = 'org.vocationsl.app://login-callback';

  /// Web addresses. employers.* opens in hiring mode and admin.* opens the
  /// admin dashboard; all of them serve the same app.
  static const websiteUrl = 'https://vocationsl.com';
  static const appUrl = 'https://app.vocationsl.com';
  static const employersUrl = 'https://employers.vocationsl.com';

  /// On the web, which role the address implies (employers.vocationsl.com).
  static bool get employerSite => kIsWeb && Uri.base.host.startsWith('employers.');

  /// On the web, whether this is admin.vocationsl.com.
  static bool get adminSite => kIsWeb && Uri.base.host.startsWith('admin.');

  static const appName = 'Vocation SL';
  static const pageSize = 10;
  static const supportEmail = 'vocationxsl@gmail.com';
  static const version = '1.0.2';
}

/// How long cached data counts as fresh before a background refresh.
class CacheTtl {
  static const jobs = Duration(minutes: 15);
  static const jobDetail = Duration(hours: 1);
  static const companies = Duration(hours: 12);
  static const user = Duration(hours: 6);
  static const applications = Duration(minutes: 5);
  static const notifications = Duration(minutes: 2);
  static const saved = Duration(minutes: 10);

  /// Cached data older than this is discarded entirely.
  static const maxAge = Duration(days: 14);
}
